pub(crate) mod edge_pass;
pub(crate) mod git_watch;
pub(crate) mod note_pass;
pub(crate) mod paint_resolver;
pub(crate) mod panel_view;
pub(crate) mod rpc;
pub(crate) mod rpc_dispatch;
pub(crate) mod session;
pub(crate) mod watch;
